# Generated by Django 5.0.2 on 2024-02-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='description',
            new_name='critical_description',
        ),
        migrations.AddField(
            model_name='snack',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
